# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from .base_model_ import Model
from .app_config_app import AppConfigApp
from .app_config_pwm import AppConfigPWM
from .. import util

from .app_config_app import AppConfigApp  # noqa: E501
from .app_config_pwm import AppConfigPWM  # noqa: E501

class AppConfig(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, app=None, pwm=None):  # noqa: E501
        """AppConfig - a model defined in OpenAPI

        :param app: The app of this AppConfig.  # noqa: E501
        :type app: AppConfigApp
        :param pwm: The pwm of this AppConfig.  # noqa: E501
        :type pwm: AppConfigPWM
        """
        self.openapi_types = {
            'app': AppConfigApp,
            'pwm': AppConfigPWM
        }

        self.attribute_map = {
            'app': 'app',
            'pwm': 'pwm'
        }

        self._app = app
        self._pwm = pwm

    @classmethod
    def from_dict(cls, dikt) -> 'AppConfig':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppConfig of this AppConfig.  # noqa: E501
        :rtype: AppConfig
        """
        return util.deserialize_model(dikt, cls)

    @property
    def app(self):
        """Gets the app of this AppConfig.


        :return: The app of this AppConfig.
        :rtype: AppConfigApp
        """
        return self._app

    @app.setter
    def app(self, app):
        """Sets the app of this AppConfig.


        :param app: The app of this AppConfig.
        :type app: AppConfigApp
        """

        self._app = app

    @property
    def pwm(self):
        """Gets the pwm of this AppConfig.


        :return: The pwm of this AppConfig.
        :rtype: AppConfigPWM
        """
        return self._pwm

    @pwm.setter
    def pwm(self, pwm):
        """Sets the pwm of this AppConfig.


        :param pwm: The pwm of this AppConfig.
        :type pwm: AppConfigPWM
        """

        self._pwm = pwm
