# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.web.api.models.base_model_ import Model
from app.web.api.models.app_fan_curve_all_of import AppFanCurveAllOf
from app.web.api.models.app_fan_curve_base import AppFanCurveBase
from app.web.api.models.app_fan_curve_series_point import AppFanCurveSeriesPoint
from app.web.api import util

from app.web.api.models.app_fan_curve_all_of import AppFanCurveAllOf  # noqa: E501
from app.web.api.models.app_fan_curve_base import AppFanCurveBase  # noqa: E501
from app.web.api.models.app_fan_curve_series_point import AppFanCurveSeriesPoint  # noqa: E501

class AppFanCurve(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, did=None, name=None, fan_curve_series=None):  # noqa: E501
        """AppFanCurve - a model defined in OpenAPI

        :param did: The did of this AppFanCurve.  # noqa: E501
        :type did: str
        :param name: The name of this AppFanCurve.  # noqa: E501
        :type name: str
        :param fan_curve_series: The fan_curve_series of this AppFanCurve.  # noqa: E501
        :type fan_curve_series: list[AppFanCurveSeriesPoint]
        """
        self.openapi_types = {
            'did': str,
            'name': str,
            'fan_curve_series': list[AppFanCurveSeriesPoint]
        }

        self.attribute_map = {
            'did': 'did',
            'name': 'name',
            'fan_curve_series': 'fanCurveSeries'
        }

        self._did = did
        self._name = name
        self._fan_curve_series = fan_curve_series

    @classmethod
    def from_dict(cls, dikt) -> 'AppFanCurve':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppFanCurve of this AppFanCurve.  # noqa: E501
        :rtype: AppFanCurve
        """
        return util.deserialize_model(dikt, cls)

    @property
    def did(self):
        """Gets the did of this AppFanCurve.

        Id of fan curve  # noqa: E501

        :return: The did of this AppFanCurve.
        :rtype: str
        """
        return self._did

    @did.setter
    def did(self, did):
        """Sets the did of this AppFanCurve.

        Id of fan curve  # noqa: E501

        :param did: The did of this AppFanCurve.
        :type did: str
        """
        if did is None:
            raise ValueError("Invalid value for `did`, must not be `None`")  # noqa: E501
        if did is not None and len(did) > 255:
            raise ValueError("Invalid value for `did`, length must be less than or equal to `255`")  # noqa: E501

        self._did = did

    @property
    def name(self):
        """Gets the name of this AppFanCurve.

        Name of the fan curve  # noqa: E501

        :return: The name of this AppFanCurve.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AppFanCurve.

        Name of the fan curve  # noqa: E501

        :param name: The name of this AppFanCurve.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501
        if name is not None and len(name) > 255:
            raise ValueError("Invalid value for `name`, length must be less than or equal to `255`")  # noqa: E501
        if name is not None and len(name) < 0:
            raise ValueError("Invalid value for `name`, length must be greater than or equal to `0`")  # noqa: E501

        self._name = name

    @property
    def fan_curve_series(self):
        """Gets the fan_curve_series of this AppFanCurve.

        Array comprised of all fan series points  # noqa: E501

        :return: The fan_curve_series of this AppFanCurve.
        :rtype: list[AppFanCurveSeriesPoint]
        """
        return self._fan_curve_series

    @fan_curve_series.setter
    def fan_curve_series(self, fan_curve_series):
        """Sets the fan_curve_series of this AppFanCurve.

        Array comprised of all fan series points  # noqa: E501

        :param fan_curve_series: The fan_curve_series of this AppFanCurve.
        :type fan_curve_series: list[AppFanCurveSeriesPoint]
        """
        if fan_curve_series is None:
            raise ValueError("Invalid value for `fan_curve_series`, must not be `None`")  # noqa: E501
        if fan_curve_series is not None and len(fan_curve_series) > 10:
            raise ValueError("Invalid value for `fan_curve_series`, number of items must be less than or equal to `10`")  # noqa: E501
        if fan_curve_series is not None and len(fan_curve_series) < 1:
            raise ValueError("Invalid value for `fan_curve_series`, number of items must be greater than or equal to `1`")  # noqa: E501

        self._fan_curve_series = fan_curve_series
