# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.web.api.models.base_model_ import Model
from app.web.api import util


class AppFanCurveSeriesPoint(Model):
    """NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).

    Do not edit the class manually.
    """

    def __init__(self, temp_in_cels=None, fan_dc_in_perc=None):  # noqa: E501
        """AppFanCurveSeriesPoint - a model defined in OpenAPI

        :param temp_in_cels: The temp_in_cels of this AppFanCurveSeriesPoint.  # noqa: E501
        :type temp_in_cels: int
        :param fan_dc_in_perc: The fan_dc_in_perc of this AppFanCurveSeriesPoint.  # noqa: E501
        :type fan_dc_in_perc: int
        """
        self.openapi_types = {
            'temp_in_cels': int,
            'fan_dc_in_perc': int
        }

        self.attribute_map = {
            'temp_in_cels': 'tempInCels',
            'fan_dc_in_perc': 'fanDcInPerc'
        }

        self._temp_in_cels = temp_in_cels
        self._fan_dc_in_perc = fan_dc_in_perc

    @classmethod
    def from_dict(cls, dikt) -> 'AppFanCurveSeriesPoint':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The AppFanCurveSeriesPoint of this AppFanCurveSeriesPoint.  # noqa: E501
        :rtype: AppFanCurveSeriesPoint
        """
        return util.deserialize_model(dikt, cls)

    @property
    def temp_in_cels(self):
        """Gets the temp_in_cels of this AppFanCurveSeriesPoint.

        The temperature in Celsius for specified `fanDcInPerc`  # noqa: E501

        :return: The temp_in_cels of this AppFanCurveSeriesPoint.
        :rtype: int
        """
        return self._temp_in_cels

    @temp_in_cels.setter
    def temp_in_cels(self, temp_in_cels):
        """Sets the temp_in_cels of this AppFanCurveSeriesPoint.

        The temperature in Celsius for specified `fanDcInPerc`  # noqa: E501

        :param temp_in_cels: The temp_in_cels of this AppFanCurveSeriesPoint.
        :type temp_in_cels: int
        """
        if temp_in_cels is None:
            raise ValueError("Invalid value for `temp_in_cels`, must not be `None`")  # noqa: E501
        if temp_in_cels is not None and temp_in_cels > 130:  # noqa: E501
            raise ValueError("Invalid value for `temp_in_cels`, must be a value less than or equal to `130`")  # noqa: E501
        if temp_in_cels is not None and temp_in_cels < -10:  # noqa: E501
            raise ValueError("Invalid value for `temp_in_cels`, must be a value greater than or equal to `-10`")  # noqa: E501

        self._temp_in_cels = temp_in_cels

    @property
    def fan_dc_in_perc(self):
        """Gets the fan_dc_in_perc of this AppFanCurveSeriesPoint.

        The fan speed for specified `tempInCels` in percent  # noqa: E501

        :return: The fan_dc_in_perc of this AppFanCurveSeriesPoint.
        :rtype: int
        """
        return self._fan_dc_in_perc

    @fan_dc_in_perc.setter
    def fan_dc_in_perc(self, fan_dc_in_perc):
        """Sets the fan_dc_in_perc of this AppFanCurveSeriesPoint.

        The fan speed for specified `tempInCels` in percent  # noqa: E501

        :param fan_dc_in_perc: The fan_dc_in_perc of this AppFanCurveSeriesPoint.
        :type fan_dc_in_perc: int
        """
        if fan_dc_in_perc is None:
            raise ValueError("Invalid value for `fan_dc_in_perc`, must not be `None`")  # noqa: E501
        if fan_dc_in_perc is not None and fan_dc_in_perc > 100:  # noqa: E501
            raise ValueError("Invalid value for `fan_dc_in_perc`, must be a value less than or equal to `100`")  # noqa: E501
        if fan_dc_in_perc is not None and fan_dc_in_perc < 0:  # noqa: E501
            raise ValueError("Invalid value for `fan_dc_in_perc`, must be a value greater than or equal to `0`")  # noqa: E501

        self._fan_dc_in_perc = fan_dc_in_perc
